### ISSUE TITLE
Fails with themes that have spaces in the name

### ISSUE THREAD

**Issue by tsbarnes** [refi64/stylepak#9]
When I try to use this with a theme that has a space in the name, it says "Theme directory did not contain any recognized GTK themes"

**Comment by refi64** [comment]
I'll check this out, but at a glance there shouldn't be any issues with this. Note that, if you're manually passing the theme name to the CLI, you'll have to quote it, since as per the regular shell parsing rules, it'll be seen by pakitheme as passing multiple arguments. (I should probably throw an error in that case...)

**Comment by tsbarnes** [comment]
It also throws an error if the theme name has certain characters in it, like parentheses. Any chance of a fix to allow themes with special characters in the name? I know flatpaks can't use those in the package name, but it should be possible to strip the invalid characters for the package name.

**Comment by resynth1943** [comment]
Not to pile on, but I can successfully reproduce this error. :+1:

**Comment by refi64** [comment]
So I *finally* had time to take a look at this, but...I don't think this is actually possible. Flatpak theme folders are mounted to paths based on the final component of their names, and that folder is how GTK looks for paths. That is to say, we could escape the characters, but then the GTK theme lookup wouldn't work.

Really though pakitheme should detect this and give notice, instead of just blindly chugging along...
